services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch-verification
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=yourpassword # Пароль для суперпользователя "elastic"
    ports:
      - "9200:9200"
    restart: always
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin  # Имя пользователя для входа
      - MINIO_ROOT_PASSWORD=yourpassword  # Пароль для входа
    ports:
      - "9000:9000"  # Порт для S3 API
      - "9001:9001"  # Порт для панели управления MinIO (Console)
    command: server /data --console-address ":9001"
    restart: always
#  postgres:
#    image: postgres:15
#    container_name: postgres
#    ports:
#      - '5435:5432'
#    environment:
#      POSTGRES_PASSWORD: "user"
#      POSTGRES_USER: "user"
#      POSTGRES_DB: "j-sso"
#    restart: always
#    volumes:
#      - ./docker/postgres/data:/var/lib/postgresql/data