
spring:

  application:
    name: verivication-dipllom
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

io:
  reflectoring:
    kafka:
      bootstrap-servers: localhost:9092
server:
  port: 8081
